# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-11 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adversario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do time')),
            ],
            options={
                'verbose_name': 'Adversário',
                'db_table': 'tb_adversario',
                'verbose_name_plural': 'Adversários',
            },
        ),
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
            ],
            options={
                'verbose_name': 'Árbitro',
                'db_table': 'tb_arbitro',
                'verbose_name_plural': 'Árbitros',
            },
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.FloatField(verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Cartão',
                'db_table': 'tb_cartao',
                'verbose_name_plural': 'Cartões',
            },
        ),
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, verbose_name='Nome da competição')),
            ],
            options={
                'verbose_name': 'Competição',
                'db_table': 'tb_competicao',
                'verbose_name_plural': 'Competições',
            },
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, verbose_name='Nome do estádio')),
            ],
            options={
                'verbose_name': 'Estádio',
                'db_table': 'tb_estadio',
                'verbose_name_plural': 'Estádios',
            },
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.PositiveIntegerField(blank=True, null=True)),
                ('finalizacao', models.CharField(blank=True, max_length=500, null=True, verbose_name='Finalização')),
                ('local', models.CharField(blank=True, max_length=500, null=True, verbose_name='Local')),
                ('origem', models.CharField(blank=True, max_length=500, null=True, verbose_name='Origem')),
            ],
            options={
                'verbose_name': 'Gol',
                'db_table': 'tb_gol',
                'verbose_name_plural': 'Gols',
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('posicao', models.PositiveSmallIntegerField(choices=[(0, 'Goleiro'), (1, 'Lateral direito'), (2, 'Lateral esquerdo')], default=0)),
            ],
            options={
                'verbose_name': 'Jogador',
                'db_table': 'tb_jogador',
                'verbose_name_plural': 'Jogadores',
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adversario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adversario_jogos', related_query_name='adversario_jogo', to='trofeu_avai.Adversario')),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitro_jogos', related_query_name='arbitro_jogo', to='trofeu_avai.Arbitro')),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competicao_jogos', related_query_name='competicao_jogo', to='trofeu_avai.Competicao')),
                ('estadio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadio_jogos', related_query_name='estadio_jogo', to='trofeu_avai.Estadio')),
                ('jogadores', models.ManyToManyField(blank=True, related_name='gols', related_query_name='gol', to='trofeu_avai.Jogador')),
            ],
            options={
                'verbose_name': 'Jogo',
                'db_table': 'tb_jogo',
                'verbose_name_plural': 'Jogos',
            },
        ),
        migrations.CreateModel(
            name='Jurado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
            ],
            options={
                'verbose_name': 'Jurado',
                'db_table': 'tb_jurado',
                'verbose_name_plural': 'Jurados',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(verbose_name='Nota')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogador_notas', related_query_name='jogador_nota', to='trofeu_avai.Jogador')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogo_notas', related_query_name='jogo_nota', to='trofeu_avai.Jogo')),
                ('jurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurado_notas', related_query_name='jurado_nota', to='trofeu_avai.Jurado')),
            ],
            options={
                'verbose_name': 'Nota',
                'db_table': 'tb_nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
            ],
            options={
                'verbose_name': 'Técnico',
                'db_table': 'tb_tecnico',
                'verbose_name_plural': 'Técnicos',
            },
        ),
        migrations.AddField(
            model_name='jogo',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnico_jogos', related_query_name='tecnico_jogo', to='trofeu_avai.Tecnico'),
        ),
        migrations.AddField(
            model_name='gol',
            name='assistente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assitente_gols', related_query_name='assitente_gol', to='trofeu_avai.Jogador'),
        ),
        migrations.AddField(
            model_name='gol',
            name='jogador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogador_gols', related_query_name='jogador_gol', to='trofeu_avai.Jogador'),
        ),
        migrations.AddField(
            model_name='gol',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogo_gols', related_query_name='jogo_gol', to='trofeu_avai.Jogo'),
        ),
        migrations.AddField(
            model_name='cartao',
            name='jogador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogador_cartoes', related_query_name='jogador_cartao', to='trofeu_avai.Jogador'),
        ),
        migrations.AddField(
            model_name='cartao',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogo_cartoes', related_query_name='jogo_cartao', to='trofeu_avai.Jogo'),
        ),
    ]
